### ISSUE TITLE
[TR] English regional strings

### ISSUE THREAD

**Issue by mikini** [froodyapp/froody-android#13]
Froody [uses the term aubergine](https://github.com/froodyapp/froody-android/blob/master/app/src/main/res/values/strings-types.xml#L56) in its English native language, where I personally know it as eggplant in English.

According to [Wikipedia](https://en.wikipedia.org/wiki/Eggplant) aubergine is used in en_GB (and probably most of Europe, including Denmark) but in en_US it is called eggplant.

Is the native language supposed to be US or UK English? Should froody have both? Maybe it could be listed as "Aubergine/eggplant"?

**Comment by gsantner** [comment]
I added an override for Eggplan in en-rUS.  
Note that I won't add en-r\* to Crowdin, because most strings are the same in most english regionals.  
This would result in much duplication. I think overwrite just some words without the use of Crowdin in sufficient.

<https://github.com/froodyapp/froody-android/blob/master/app/src/main/res/values-en-rUS/strings-types.xml>

**Comment by mikini** [comment]
Sounds sensible to keep complexity down. Smart way to handle a regional override (not that familiar with the Android SDK). I didn't find any other terms that seemed to be off. Although I am not very fluent in the finer regional differences of US vs. GB.

Yeah, the default should have a global reach as far as possible. It seems like aubergine is indeed more common (in the scripts I can read at least), they probably all originate from the Latin term.
