### ISSUE TITLE
Have a switch to show free offers only

### ISSUE THREAD

**Issue by merge** [froodyapp/froody-android#20]
It'd be nice to have a switch for hiding all for-pay offers on the map. If so, make it "lightweight" (a local view change) and always accessible when viewing the map.

It would underline the focus on not letting fruits rot away :)

**Comment by gsantner** [comment]
Good idea. 

I just see a problem with this on devices with a small screen.

* One button alone will be not very descriptive with just the icon: Think it would need some sort description
* Multiple buttons (bar): Takes too much space
* One button (displaying [floating submenu](https://i.stack.imgur.com/ZFN85.png)): Would have just one option
  * Theres already the "More" category
  * There are already settings

![unbenannt](https://cloud.githubusercontent.com/assets/6735650/26402807/01fd7e04-408c-11e7-9d77-ed8492ba9127.png)

I would personally put it in the app's settings, because either you are mainly interested in "completly free" offers, or not. Or to more generalize this: Why not provide options in the settings to tick off what all should be displayed (e.g. one could tick on "Free", "Donation")  and not just a single switch.

**Comment by merge** [comment]
I guess it would indeed equally well fit into the settings

**Comment by gsantner** [comment]
This is implemented now, will be included in next release. Thanks for suggesting the feature.

![screenshot_20170611-174824](https://user-images.githubusercontent.com/6735650/27012343-3e88fa92-4ece-11e7-8475-bdbf8ad87560.png)

**Comment by merge** [comment]
looks nice! thanks for writing this feature
